### ISSUE TITLE
How to use in front-end form

### ISSUE THREAD

**Issue by freeyland** [vojtasvoboda/oc-locationtowns-plugin#7]
From the location plugin I get

`
{% set countryId = countryId|default(form_value('country_id')) %}
{% set stateId = stateId|default(form_value('state_id')) %}

<div class="form-group">
    <label for="accountCountry">Country</label>
    {{ form_select_country('country_id', countryId, {
        id: 'accountCountry',
        class: 'form-control',
        emptyOption: '',
        'data-request': 'onInit',
        'data-request-update': {
            'country-state': '#partialCountryState'
        }
    }) }}
</div>

<div class="form-group">
    <label for="accountState">State</label>
    {{ form_select_state('state_id', countryId, stateId, {
        id: 'accountState',
        class: 'form-control',
        emptyOption: ''
    }) }}
</div>
`

How to add the town dropdown?
`
<div class="form-group">
    <label for="accountTown">Town</label>
    {{ form_select_state('state_id', townId, townId, {
        id: 'accountTown',
        class: 'form-control',
        emptyOption: ''
    }) }}
</div>
`

How to make the page refresh on change of state?

**Comment by vojtasvoboda** [comment]
I'm sorry, but this feature is not implemented in this plugin. There is no function `form_select_town`.

**Comment by mennax** [comment]
> I'm sorry, but this feature is not implemented in this plugin. There is no function `form_select_town`.

I don't understand. There is this function. This is my partial:

```
{% set countryId = countryId|default(form_value('property[country_id]')) %}
{% set stateId = stateId|default(form_value('property[state_id]')) %}
{% set townId = townId|default(form_value('property[town_id]')) %}
<p>
<div class="form-group">
    <label for="accountCountry">Country</label>
    {{ form_select_country('property[country_id]', countryId, {
        id: 'accountCountry',
        class: 'w3-input w3-border',
        emptyOption: '',
        'data-request': 'onInit',
        'data-request-update': {
            ('buddies/location/country_state_town'): '#partialCountryState'
        }
    }) }}
</div>

<div class="form-group">
    <label for="accountState">State</label>
    {{ form_select_state('property[state_id]', countryId, stateId, {
        id: 'accountState',
        class: 'w3-input w3-border',
        emptyOption: '',
        'data-request': 'onInit',
        'data-request-update': {
            ('buddies/location/country_state_town'): '#partialCountryState'
        }
    }) }}
</div>

<div class="form-group">
    <label for="accountState">Town</label>
    {{ form_select_town('property[town_id]', stateId, townId, {
        id: 'accountTown',
        class: 'w3-input w3-border',
        emptyOption: ''

    }) }}
</div>
```

**Comment by vojtasvoboda** [comment]
Sorry for the late reply. There is a working example of country-state-town partial:

```
{% set countryId = countryId|default(form_value('country_id')) %}
{% set stateId = stateId|default(form_value('state_id')) %}
{% set townId = townId|default(form_value('town_id')) %}

{{ form_open() }}
    <div class="form-group">
        <label for="accountCountry">Country</label>
        {{ form_select_country('country_id', countryId, {
            id: 'accountCountry',
            class: 'form-control',
            emptyOption: '',
            'data-request': 'onInit',
            'data-request-update': {
                'country-state': '#partialCountryState'
            }
        }) }}
    </div>

    <div class="form-group">
        <label for="accountState">State</label>
        {{ form_select_state('state_id', countryId, stateId, {
            id: 'accountState',
            class: 'form-control',
            emptyOption: '',
            'data-request': 'onInit',
            'data-request-update': {
                'country-state': '#partialCountryState'
            }
        }) }}
    </div>

    <div class="form-group">
        <label for="accountTown">Town</label>
        {{ form_select_town('town_id', stateId, townId, {
            id: 'accountTown',
            class: 'form-control',
            emptyOption: ''
        }) }}
    </div>
{{ form_close() }}
```

Tested on October v2. Almost same as your example, but I've used also {{ form_open() }} and {{ form_close() }}.
